import type { Metadata } from "next";
import { Inter, Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({weight: ['400'], subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="js/fontawesome.js" ></Script>
      <body className={poppins.className} >{children}</body>
    </html>
  );
}
